#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/python/libexec/bin
  ${ZDOTDIR:-$HOME}/.node/bin
  ${ZDOTDIR:-$HOME}/.fastlane/bin
  ${ZDOTDIR:-$HOME}/Library/Android/sdk/tools
  ${ZDOTDIR:-$HOME}/Library/Android/sdk/platform-tools
  ${ZDOTDIR:-$HOME}/Documents/Development/Mobile/Flutter/flutter/bin
  $path
)

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

export ANDROID_HOME="/Users/danielchong/Library/Android/sdk"
export ANDROID_NDK="/Users/danielchong/Library/Android/android-ndk-r10e"
export JAVA_HOME=$(/usr/libexec/java_home)