#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/go/libexec/bin
  /Library/TeX/texbin
  ${ZDOTDIR:-$HOME}/.node/bin
  ${ZDOTDIR:-$HOME}/.fastlane/bin
  ${ZDOTDIR:-$HOME}/Library/Android/sdk/build-tools/23.0.1
  ${ZDOTDIR:-$HOME}/Library/Android/sdk/tools
  ${ZDOTDIR:-$HOME}/Library/Android/sdk/platform-tools
  ${ZDOTDIR:-$HOME}/Documents/Development/Other/go/bin
  ${ZDOTDIR:-$HOME}/Downloads/google-cloud-sdk/bin
  ${ZDOTDIR:-$HOME}/Documents/Development/Mobile/Flutter/flutter/bin
  ${ZDOTDIR:-$HOME}/Documents/Development/Mobile/Flutter/flutter/.pub-cache/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"


export UNITY_5_6_3p1_PATH="/Applications/Unity_Hub/Hub/Editor/5.6.3p1/Unity.app/Contents/MacOS"

export ANDROID_HOME="/Users/danielchong/Library/Android/sdk"
export ANDROID_NDK="/Users/danielchong/Library/Android/android-ndk-r10e"
export GOPATH="/Users/danielchong/Documents/Development/Other/go"
export GOBIN="/Users/danielchong/Documents/Development/Other/go/bin"
# export JAVA_HOME=$(/usr/libexec/java_home)
# alias elm-format='elm-format-0.17'

# The next line enables shell command completion for gcloud.
if [ -f '/Users/danielchong/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/danielchong/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# eval "$(rbenv init -)"